import { assertCatalog } from "./catalog-check.js";

const PERSON_DICTIONARY =
  "https://redatam.indec.gob.ar/binarg/RpWebStats.exe/Dictionary?BASE=CPV2022&ITEM=DICPOB&lang=ESP";
const HOUSEHOLD_DICTIONARY =
  "https://redatam.indec.gob.ar/binarg/RpWebStats.exe/Dictionary?BASE=CPV2022&ITEM=DICHOG&lang=ESP";
const DWELLING_DICTIONARY =
  "https://redatam.indec.gob.ar/binarg/RpWebStats.exe/Dictionary?BASE=CPV2022&ITEM=DICVIV&lang=ESP";
const GEOGRAPHY_DICTIONARY =
  "https://redatam.indec.gob.ar/binarg/RpWebStats.exe/Dictionary?BASE=CPV2022&ITEM=DICGEO&lang=ESP";
const OFFICIAL_DEFINITIONS =
  "https://redatam.indec.gob.ar/redarg/CENSOS/CPV2022/Docs/Redatam_Definiciones_de_la_base_de_datos.pdf";

export const CPV2022_VP_CATALOG_V0 = assertCatalog({
  contract: "argentina.census-catalog/v1",
  catalog_id: "arg-cpv2022-vp-semantic-v0",
  census_vintage: 2022,
  database: "VP",
  source_release_label: "april-2025",
  official_redatam_base: "CPV2022",
  universe: {
    id: "vp",
    database: "VP",
    label: "Personas, hogares y viviendas particulares",
    concepts: ["private-dwellings-census"],
    aliases: ["vp", "viviendas particulares"],
    description:
      "Universo VP del Censo 2022; no representa automáticamente todos los universos censales.",
    evidence_ids: ["adapter-vp-contract", "official-person-dictionary"],
  },
  evidence: [
    {
      id: "official-person-dictionary",
      kind: "official_web_dictionary",
      locator: PERSON_DICTIONARY,
      note: "Current CPV2022 person-variable names, labels, aliases and ranges.",
    },
    {
      id: "official-household-dictionary",
      kind: "official_web_dictionary",
      locator: HOUSEHOLD_DICTIONARY,
      note: "Current CPV2022 household-variable names, labels, aliases and ranges.",
    },
    {
      id: "official-dwelling-dictionary",
      kind: "official_web_dictionary",
      locator: DWELLING_DICTIONARY,
      note: "Current CPV2022 dwelling-variable names, labels, aliases and ranges.",
    },
    {
      id: "official-geography-dictionary",
      kind: "official_web_dictionary",
      locator: GEOGRAPHY_DICTIONARY,
      note: "Current CPV2022 PROV/DPTO geography identifiers.",
    },
    {
      id: "official-definitions",
      kind: "official_definitions",
      locator: OFFICIAL_DEFINITIONS,
      note: "Official CPV2022 definitions and coded category labels.",
    },
    {
      id: "project-relational-schema",
      kind: "project_schema",
      locator:
        "rxdb-extractor:docs/forensics/evidence/arg2022_schema.tsv",
      note:
        "Preserved relational schema evidence used to keep v0 on variables shared with the locally qualified lineage.",
    },
    {
      id: "adapter-vp-contract",
      kind: "project_contract",
      locator:
        "argentina-censo2022-rxdb:src/argentina_censo2022_rxdb/profile.py",
      note: "VP entity hierarchy and supported relational entity contract.",
    },
  ],
  entities: [
    {
      id: "VIVIENDA",
      universe_id: "vp",
      label: "Vivienda particular",
      concepts: ["dwelling"],
      aliases: ["vivienda", "viviendas"],
      supports_count: true,
      evidence_ids: ["official-dwelling-dictionary", "adapter-vp-contract"],
    },
    {
      id: "HOGAR",
      universe_id: "vp",
      label: "Hogar",
      concepts: ["household"],
      aliases: ["hogar", "hogares"],
      supports_count: true,
      evidence_ids: ["official-household-dictionary", "adapter-vp-contract"],
    },
    {
      id: "PERSONA",
      universe_id: "vp",
      label: "Persona",
      concepts: ["person"],
      aliases: ["persona", "personas", "poblacion", "población"],
      supports_count: true,
      evidence_ids: ["official-person-dictionary", "adapter-vp-contract"],
    },
  ],
  relationships: [
    {
      child: "HOGAR",
      parent: "VIVIENDA",
      kind: "belongs_to",
      evidence_ids: ["adapter-vp-contract", "project-relational-schema"],
    },
    {
      child: "PERSONA",
      parent: "HOGAR",
      kind: "belongs_to",
      evidence_ids: ["adapter-vp-contract", "project-relational-schema"],
    },
  ],
  variables: [
    {
      id: "PERSONA.EDAD",
      source_identifier: "EDAD",
      source_alias: null,
      entity: "PERSONA",
      universe_id: "vp",
      label: "Edad",
      value_type: "integer",
      range: { min: 0, max: 110 },
      concepts: ["age"],
      aliases: ["edad", "años", "anos"],
      allowed_operators: ["eq", "neq", "gt", "gte", "lt", "lte", "between", "in"],
      supports_average: true,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "none",
      anomaly: null,
      evidence_ids: ["official-person-dictionary", "project-relational-schema"],
    },
    {
      id: "PERSONA.P02",
      source_identifier: "P02",
      source_alias: "SEXO",
      entity: "PERSONA",
      universe_id: "vp",
      label: "Sexo registrado al nacer",
      value_type: "categorical",
      range: { min: 1, max: 2 },
      concepts: ["sex-at-birth"],
      aliases: ["sexo", "sexo registrado al nacer"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "complete",
      anomaly: null,
      evidence_ids: [
        "official-person-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "PERSONA.P06",
      source_identifier: "P06",
      source_alias: "ASISTE",
      entity: "PERSONA",
      universe_id: "vp",
      label: "Cursa o asiste a algún establecimiento educativo",
      value_type: "categorical",
      range: { min: 1, max: 2 },
      concepts: ["school-attendance"],
      aliases: ["asistencia educativa", "asiste a un establecimiento educativo"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "complete",
      anomaly: null,
      evidence_ids: [
        "official-person-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "PERSONA.P07",
      source_identifier: "P07",
      source_alias: "NIVEL",
      entity: "PERSONA",
      universe_id: "vp",
      label: "Nivel educativo que está cursando",
      value_type: "categorical",
      range: { min: 1, max: 7 },
      concepts: ["current-education-level"],
      aliases: ["nivel educativo actual", "nivel que cursa"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "complete",
      anomaly: null,
      evidence_ids: [
        "official-person-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "PERSONA.AESC",
      source_identifier: "AESC",
      source_alias: null,
      entity: "PERSONA",
      universe_id: "vp",
      label: "Años de escolaridad completos",
      value_type: "integer",
      range: { min: 0, max: 99 },
      concepts: ["completed-school-years"],
      aliases: ["años de escolaridad", "anos de escolaridad"],
      allowed_operators: [],
      supports_average: false,
      supports_breakdown: false,
      status: "experimental",
      category_coverage: "none",
      anomaly:
        "Code 99 means Ignorado; ordered comparisons/averages stay disabled until special-value semantics are modeled.",
      evidence_ids: [
        "official-person-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "PERSONA.HNVUA",
      source_identifier: "HNVUA",
      source_alias: null,
      entity: "PERSONA",
      universe_id: "vp",
      label: "Hija o hijo nacido vivo el último año",
      value_type: "categorical",
      range: { min: 1, max: 2 },
      concepts: ["live-birth-last-year"],
      aliases: ["hijo nacido vivo ultimo año"],
      allowed_operators: [],
      supports_average: false,
      supports_breakdown: false,
      status: "blocked",
      category_coverage: "none",
      anomaly:
        "Name/alias ambiguity under the RedEngine runtimes qualified by the extraction project.",
      evidence_ids: ["official-person-dictionary", "adapter-vp-contract"],
    },
    {
      id: "HOGAR.TOTPOBH",
      source_identifier: "TOTPOBH",
      source_alias: null,
      entity: "HOGAR",
      universe_id: "vp",
      label: "Cantidad de personas en el hogar",
      value_type: "integer",
      range: { min: 1, max: 70 },
      concepts: ["household-size"],
      aliases: ["tamaño del hogar", "tamano del hogar", "personas en el hogar"],
      allowed_operators: ["eq", "neq", "gt", "gte", "lt", "lte", "between", "in"],
      supports_average: true,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "none",
      anomaly: null,
      evidence_ids: ["official-household-dictionary", "project-relational-schema"],
    },
    {
      id: "HOGAR.H20",
      source_identifier: "H20",
      source_alias: "TOTHAB",
      entity: "HOGAR",
      universe_id: "vp",
      label: "Total de habitaciones o piezas",
      value_type: "integer",
      range: { min: 1, max: 30 },
      concepts: ["room-count"],
      aliases: ["habitaciones", "piezas", "cantidad de habitaciones"],
      allowed_operators: ["eq", "neq", "gt", "gte", "lt", "lte", "between", "in"],
      supports_average: true,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "none",
      anomaly: null,
      evidence_ids: ["official-household-dictionary", "project-relational-schema"],
    },
    {
      id: "HOGAR.H22",
      source_identifier: "H22",
      source_alias: "REGTEN",
      entity: "HOGAR",
      universe_id: "vp",
      label: "Propiedad de la vivienda",
      value_type: "categorical",
      range: { min: 1, max: 5 },
      concepts: ["housing-tenure"],
      aliases: ["tenencia de la vivienda", "propiedad de la vivienda"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "complete",
      anomaly: null,
      evidence_ids: [
        "official-household-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "HOGAR.H24A",
      source_identifier: "H24A",
      source_alias: "INTERNET",
      entity: "HOGAR",
      universe_id: "vp",
      label: "El hogar tiene internet en la vivienda",
      value_type: "categorical",
      range: { min: 1, max: 2 },
      concepts: ["home-internet"],
      aliases: ["internet en la vivienda", "internet del hogar"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "complete",
      anomaly: null,
      evidence_ids: [
        "official-household-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "HOGAR.NBI_TOT",
      source_identifier: "NBI_TOT",
      source_alias: null,
      entity: "HOGAR",
      universe_id: "vp",
      label: "Necesidades básicas insatisfechas",
      value_type: "categorical",
      range: { min: 1, max: 2 },
      concepts: ["unmet-basic-needs"],
      aliases: ["nbi", "necesidades basicas insatisfechas", "necesidades básicas insatisfechas"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "complete",
      anomaly: null,
      evidence_ids: [
        "official-household-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "VIVIENDA.V01",
      source_identifier: "V01",
      source_alias: "TIPOVIV",
      entity: "VIVIENDA",
      universe_id: "vp",
      label: "Tipo de vivienda",
      value_type: "categorical",
      range: { min: 1, max: 31 },
      concepts: ["dwelling-type"],
      aliases: ["tipo de vivienda"],
      allowed_operators: ["eq", "neq", "in"],
      supports_average: false,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "partial",
      anomaly: null,
      evidence_ids: [
        "official-dwelling-dictionary",
        "official-definitions",
        "project-relational-schema",
      ],
    },
    {
      id: "VIVIENDA.V06",
      source_identifier: "V06",
      source_alias: "TOTHOG",
      entity: "VIVIENDA",
      universe_id: "vp",
      label: "Cantidad de hogares",
      value_type: "integer",
      range: { min: 1, max: 30 },
      concepts: ["households-in-dwelling"],
      aliases: ["hogares en la vivienda", "cantidad de hogares por vivienda"],
      allowed_operators: ["eq", "neq", "gt", "gte", "lt", "lte", "between", "in"],
      supports_average: true,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "none",
      anomaly: null,
      evidence_ids: ["official-dwelling-dictionary", "project-relational-schema"],
    },
    {
      id: "VIVIENDA.TOTPOBV",
      source_identifier: "TOTPOBV",
      source_alias: null,
      entity: "VIVIENDA",
      universe_id: "vp",
      label: "Cantidad de personas en la vivienda",
      value_type: "integer",
      range: { min: 1, max: 6000 },
      concepts: ["persons-in-dwelling"],
      aliases: ["personas en la vivienda"],
      allowed_operators: ["eq", "neq", "gt", "gte", "lt", "lte", "between", "in"],
      supports_average: true,
      supports_breakdown: true,
      status: "supported",
      category_coverage: "none",
      anomaly: null,
      evidence_ids: ["official-dwelling-dictionary", "project-relational-schema"],
    },
  ],
  categories: [
    { variable: "PERSONA.P02", code: 1, label: "Mujer/Femenino", concepts: ["woman"], aliases: ["mujer", "mujeres", "femenino"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P02", code: 2, label: "Varón/Masculino", concepts: ["man"], aliases: ["varon", "varón", "varones", "masculino"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P06", code: 1, label: "Sí", concepts: ["attends-education"], aliases: ["asiste", "estudia actualmente"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P06", code: 2, label: "No", concepts: ["does-not-attend-education"], aliases: ["no asiste"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 1, label: "Jardín maternal, guardería, centro de cuidado, salas de 0 a 3", concepts: ["early-childhood-care"], aliases: ["jardin maternal", "guarderia"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 2, label: "Sala de 4 o 5", concepts: ["preprimary"], aliases: ["sala de 4", "sala de 5", "preescolar"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 3, label: "Primario", concepts: ["primary-education"], aliases: ["primario", "primaria"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 4, label: "Secundario", concepts: ["secondary-education"], aliases: ["secundario", "secundaria"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 5, label: "Terciario no universitario", concepts: ["tertiary-nonuniversity"], aliases: ["terciario no universitario"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 6, label: "Universitario de grado", concepts: ["university-degree"], aliases: ["universitario de grado", "universidad de grado"], evidence_ids: ["official-definitions"] },
    { variable: "PERSONA.P07", code: 7, label: "Posgrado", concepts: ["postgraduate"], aliases: ["posgrado", "maestria", "maestría", "doctorado"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H22", code: 1, label: "Propia", concepts: ["owned"], aliases: ["propia", "propietario", "propietaria"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H22", code: 2, label: "Alquilada", concepts: ["rented"], aliases: ["alquilada", "alquila", "alquiler"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H22", code: 3, label: "Cedida por trabajo", concepts: ["employer-provided"], aliases: ["cedida por trabajo"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H22", code: 4, label: "Prestada", concepts: ["borrowed"], aliases: ["prestada"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H22", code: 5, label: "Otra situación", concepts: ["other-tenure"], aliases: ["otra situacion", "otra situación"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H24A", code: 1, label: "Sí", concepts: ["has-home-internet"], aliases: ["con internet", "tiene internet"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.H24A", code: 2, label: "No", concepts: ["no-home-internet"], aliases: ["sin internet", "no tiene internet"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.NBI_TOT", code: 1, label: "Sí", concepts: ["has-unmet-basic-needs"], aliases: ["con nbi", "tiene nbi"], evidence_ids: ["official-definitions"] },
    { variable: "HOGAR.NBI_TOT", code: 2, label: "No", concepts: ["no-unmet-basic-needs"], aliases: ["sin nbi"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 1, label: "Casa", concepts: ["house"], aliases: ["casa", "casas"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 2, label: "Rancho", concepts: ["ranch-dwelling"], aliases: ["rancho", "ranchos"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 3, label: "Casilla", concepts: ["shack"], aliases: ["casilla", "casillas"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 4, label: "Departamento", concepts: ["apartment"], aliases: ["departamento", "departamentos"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 5, label: "Pieza en inquilinato, hotel familiar o pensión", concepts: ["tenement-room"], aliases: ["pieza en inquilinato", "pension"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 6, label: "Local no construido para habitación ocupado", concepts: ["nonresidential-premises"], aliases: ["local no construido para habitacion"], evidence_ids: ["official-definitions"] },
    { variable: "VIVIENDA.V01", code: 7, label: "Vivienda móvil ocupada", concepts: ["mobile-dwelling"], aliases: ["vivienda movil", "vivienda móvil"], evidence_ids: ["official-definitions"] }
  ],
  geographies: [
    {
      level: "PROV",
      source_identifier: "IDPROV",
      label: "Provincia",
      concepts: ["province"],
      aliases: ["provincia", "provincias"],
      supports_breakdown: true,
      member_coverage: "none",
      members: [],
      evidence_ids: ["official-geography-dictionary"],
    },
    {
      level: "DPTO",
      source_identifier: "IDPTO",
      label: "Departamento",
      concepts: ["department"],
      aliases: ["departamento", "departamentos", "partido", "partidos"],
      supports_breakdown: true,
      member_coverage: "none",
      members: [],
      evidence_ids: ["official-geography-dictionary"],
    },
  ],
});
